extends Node3D
# Auto-generated by spline_mesh_placer.py
# Loads and places all converted Spline Mesh GLBs at their Unity world positions.

const PLACEMENT_PATH = "res://courses/The_Old_Course_mesh_placement.json"

func _ready():
	_load_meshes()

func _load_meshes():
	var file = FileAccess.open(PLACEMENT_PATH, FileAccess.READ)
	if not file: push_error("SplineMeshLoader: cannot open " + PLACEMENT_PATH); return
	var data = JSON.parse_string(file.get_as_text())
	file.close()
	if not data: return
	var loaded := 0
	for entry in data.placements:
		# Skip unclassified meshes — "other" entries often carry stray water/sea geometry
		# from the original Unity assets with baked-in blue materials.
		if entry.get("type", "other") == "other":
			continue
		var glb_path: String = "res://" + entry.mesh_file if not entry.mesh_file.begins_with("res://") else entry.mesh_file
		if not ResourceLoader.exists(glb_path): continue
		var scene = load(glb_path)
		if not scene: continue
		var inst = scene.instantiate()
		inst.position = Vector3(entry.godot_x, entry.godot_y, entry.godot_z)
		add_child(inst)
		loaded += 1
	print("SplineMeshLoader: placed %d meshes" % loaded)
